version: '3.8'
services:
    java-maven-app:
      image: weridcoder/my-repo:java-maven-2.0.0
      ports:
        - 8000:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
